name: CI

on:
  push:
    branches:
      - main
      - InitialPrototype
  workflow_dispatch:  # Add this line to enable manual workflow dispatch
    
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move up a level
        run: cd ..

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          sudo apt-get install -y python3

        

      - name: Compile and run mock automation test
        run: |
          gcc src/CICDtest.c -o .\output\CICDtest.exe
          ./output/CICDtest.exe

      # - name: Compile and run mock Vehicle Control Unit
      #   run: |
      #     gcc src/DownstreamUDP.c -o output/rcv.exe
      #     ./output/rcv.exe 8080

      # - name: Run Python script
      #   run: python3 src/Upstream.py
        
      # - name: Mimick Interprocess Communication 
      #   run: echo "Mock transmission data" | python3 /src/Upstream.py

      # - name: Terminate Python script 
      #   run: echo "!" | python3 /src/Upstream.py

